name: Deploy pm file manager to AWS CloudFormation

on:
  push:
    branches:
      - main

jobs:
  deploy-cloudformation:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ vars.AWS_ACCOUNT_ID_TEST }}:role/${{ vars.AWS_ROLE_NAME }}
          aws-region: us-east-1
      - name: Deploy AWS CloudFormation Stack
        uses: aws-actions/aws-cloudformation-github-deploy@v1
        with:
          name: pm-document-management-stack-v2
          template: template.yaml
          capabilities: CAPABILITY_NAMED_IAM,CAPABILITY_IAM
          no-fail-on-empty-changeset: "1"